### ISSUE TITLE
add dependency for curses

### ISSUE THREAD

**Issue by pocke** [pocke/flowterm#2]
```
/usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- curses (LoadError)
	from /usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/pocke/.gem/ruby/2.4.0/gems/flowterm-0.1.0/lib/flowterm.rb:1:in `<top (required)>'
	from /usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/pocke/.gem/ruby/2.4.0/gems/flowterm-0.1.0/exe/flowterm:3:in `<top (required)>'
	from /home/pocke/.gem/ruby/2.4.0/bin//flowterm:22:in `load'
	from /home/pocke/.gem/ruby/2.4.0/bin//flowterm:22:in `<main>'
	from /usr/bin/ruby_executable_hooks:15:in `eval'
	from /usr/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pocke** [comment]
done
